---
name: Release
on:
  # push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      pve_version:
        required: false
        default: ""
        description: Proxmox VE version (оставьте пустым для автоматического определения)
        type: string

      pve_sha256:
        required: false
        default: ""
        description: Proxmox VE SHA256 (оставьте пустым для пропуска проверки)
        type: string

jobs:
  release:
    name: ISO release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      packages: write
    env:
      COMMIT_SHORT_SHA: null
      PROXMOX_VERSION: ${{ inputs.pve_version || '' }}
      PROXMOX_ISO_SHA: ${{ inputs.pve_sha256 != '' && inputs.pve_sha256 || 'skip' }}

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4.2.2

      - name: Set short git commit SHA
        run: |+
          set -eux

          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Auto-detect Proxmox version if not provided
        run: |+
          set -eux

          if [ -z "${PROXMOX_VERSION}" ]; then
            echo "Автоматическое определение последней версии Proxmox VE..."
            DETECTED_VERSION=$(curl -s https://enterprise.proxmox.com/iso/ | grep -oP 'proxmox-ve_\K[0-9]+\.[0-9]+-[0-9]+' | sort -V | tail -1)
            echo "Найдена версия: ${DETECTED_VERSION}"
            echo "PROXMOX_VERSION=${DETECTED_VERSION}" >> $GITHUB_ENV
          else
            echo "Используется указанная версия: ${PROXMOX_VERSION}"
          fi

      - name: Create Directory
        run: |+
          set -eux

          mkdir -p answers dist

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build auto install ISO from Proxmox VE
        uses: naa0yama/proxmox-auto-install-iso@v1
        with:
          pve_version: ${{ env.PROXMOX_VERSION }}
          pve_sha256: ${{ env.PROXMOX_ISO_SHA == 'skip' && '' || env.PROXMOX_ISO_SHA }}

      - name: Cleanup pre-releases
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |+
            const __prereleases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });
            const prereleases = __prereleases.data

            for (const index in prereleases) {
              if (prereleases[index].prerelease == true || prereleases[index].draft == true) {
                console.log('delete ' + prereleases[index]['id'] + '\t' + prereleases[index]['name'])

                await github.rest.repos.deleteRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: prereleases[index]['id'],
                });
              }
            }

            console.log('end run')

      - name: Calculate the sha256sum
        working-directory: dist
        run: |+
          set -eux

          sha256sum proxmox-ve_${PROXMOX_VERSION}_auto_* > sha256sum.txt
          ls -lah .

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          name: Proxmox VE ${{ env.PROXMOX_VERSION }} ${{ env.COMMIT_SHORT_SHA }}
          tag_name: ${{ env.COMMIT_SHORT_SHA }}
          generate_release_notes: true
          draft: true
          prerelease: false
          make_latest: true
          files: |
            ./dist/proxmox-ve_${{ env.PROXMOX_VERSION }}_auto_*.iso
            ./dist/sha256sum.txt
